#!/usr/bin/env bash
# Bash script that displays Best School 10 times while loop.

i=0

while (( i < 10 ))

do
    echo "Best School"

    (( i++ ))

    if (( i == 9))

    then

        echo "Hi"

    fi  
done

