#!/usr/bin/env bash
# Bash script that displays Best School 10 times while loop.

i=1

while (( i <= 10 ))

do
    if (( i == 4))

    then
        echo "bad luck"

    elif (( i == 8))

    then
        echo "good luck"

    else
        echo "Best School"

    fi  
    (( i++ ))
done

